name: Java CI

on:
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build via Gradle
      run: cd java; chmod +x gradlew; ./gradlew check --parallel --continue
    - name: Compress build files
      if: always()
      run: zip -r dataflow-build.zip java/dataflow/build/reports; zip -r judge-build.zip java/judge/build/reports
    - name: Upload dataflow-build
      uses: actions/upload-artifact@v1
      if: always()
      with:
        name: dataflow-build
        path: dataflow-build.zip
    - name: Upload judge-build
      uses: actions/upload-artifact@v1
      if: always()
      with:
        name: judge-build
        path: judge-build.zip
